name: CI/CD Pipeline Athalah

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ===== BACKEND BUILD & TEST =====
      - name: Install Backend Dependencies
        working-directory: ./backend-rpic
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend-rpic
        run: |
          if [ -f "test" ]; then
            npm test
          else
            echo "No backend test configured"
          fi

      # ===== FRONTEND BUILD & TEST =====
      - name: Install Frontend Dependencies
        working-directory: ./frontend-rpic
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend-rpic
        run: |
          if [ -f "test" ]; then
            npm test
          else
            echo "No frontend test configured"
          fi

      - name: Build Frontend
        working-directory: ./frontend-rpic
        run: npm run build

      # OPTIONAL: Docker deployment ke local (dapat di-simulasikan)
      # - name: Install Docker
      #   uses: docker/setup-buildx-action@v3

      # - name: Build Docker Images
      #   run: |
      #     docker build -t rpic-backend ./backend-rpic
      #     docker build -t rpic-frontend ./frontend-rpic

      # - name: Run with Docker Compose
      #   run: |
      #     echo "version: '3'
      #     services:
      #       backend:
      #         image: rpic-backend
      #         ports:
      #           - 5000:5000
      #       frontend:
      #         image: rpic-frontend
      #         ports:
      #           - 3000:80" > docker-compose.yml
      #     docker-compose up -d
