name: Continuous Delivery Athallah

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build Frontend
      - name: Install and Build Frontend
        working-directory: frontend-rpic
        run: |
          npm install
          npm run build

      # Install Backend dependencies
      - name: Install Backend Dependencies
        working-directory: backend-rpic
        run: npm install

      # Simulate delivery: copy built files to delivery folder
      - name: Archive frontend build
        run: |
          mkdir -p delivery-artifacts/frontend
          cp -r frontend-rpic/dist/* delivery-artifacts/frontend/

      - name: Archive backend source
        run: |
          mkdir -p delivery-artifacts/backend
          cp -r backend-rpic/* delivery-artifacts/backend/
