name: CD Deploy Athallah

on:
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # === FRONTEND ===
    - name: Setup Node.js for frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./frontend-rpic
      run: npm install

    - name: Build frontend
      working-directory: ./frontend-rpic
      run: npm run build

    # === BACKEND ===
    - name: Setup Node.js for backend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./backend-rpic
      run: npm install

    # Optional: Jalankan test
    # - name: Run backend tests
    #   working-directory: ./backend-rpic
    #   run: npm test

    # === DEPLOYMENT STEP ===
    # Ubah bagian ini sesuai cara kamu deploy:
    # - SSH ke VPS
    # - Push ke layanan hosting
    # - Deploy ke Vercel, Railway, dll
    # Contoh deploy ke VPS pakai SSH:
    - name: Deploy to VPS (optional)
      if: github.event_name == 'release'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/your-user/app-dir
          git pull origin master
          cd frontend-rpic && npm install && npm run build
          cd ../backend-rpic && npm install && pm2 restart backend-app
